version: '3.8'

services:
  # The FastAPI Application Service
  api:
    build:
      # This specifies the build context, which is
      # the directory containing all the files and folders
      # that will be sent to the Docker daemon for the build.
      # This includes your source code and, most importantly, the Dockerfile.
      # The dot is a universal shorthand in command-line environments
      # for the current directory.
      context: .
    # Give the built image a name
    image: image-augmentation-service-api:latest
    # Give the running container a name
    container_name: image-augmentation-api
    ports:
      - "8000:8000"